name: regresion-demo
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - jupyter-book
  - pip
  - pip:
      - myst-nb
      - sphinx-external-toc