name: Build and Deploy Jupyter Book

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.11
          activate-environment: regresion-demo
          use-mamba: true
          miniforge-version: latest

      - name: Verify environment
        shell: bash -l {0}
        run: |
          echo "=== Conda info ==="
          conda info
          echo "=== Installed packages ==="
          conda list
          echo "=== Python path ==="
          which python
          echo "=== Jupyter Book version ==="
          jupyter-book --version

      - name: Build Jupyter Book
        shell: bash -l {0}
        run: |
          cd book
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
