name: Build and Deploy Jupyter Book

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda and create environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          # evita activar la base; la acci칩n crear치 y har치 disponible el entorno
          auto-activate-base: false
          environment-file: environment.yml
          environment-name: regresion-demo

      - name: Debug: show conda info and list envs
        run: |
          conda info
          conda env list

      - name: Install extra pip packages (if needed)
        run: |
          conda run -n regresion-demo pip install --upgrade pip
          conda run -n regresion-demo pip install ghp-import

      - name: Build Jupyter Book (run inside conda env)
        run: |
          # Ejecuta la construcci칩n desde la carpeta `book`
          conda run -n regresion-demo jupyter-book build book
        # opcional: cambia working-directory si prefieres
        # working-directory: book

      - name: Show build folder listing (debug)
        run: |
          ls -la book/_build || true
          ls -la book/_build/html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html
